codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "50...100"

ignore:
  - HospitalAPI/Global.asax.cs
  - HospitalAPI/Migrations/.*
  - HospitalAPI/Areas/.*
  - HospitalAPI/App_Start/.*


